name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish extract on version change
        id: publish_nuget_extract
        uses: gaspra/gaspra.publishdotnetnuget@v1
        with:
          PROJECT_FILE_PATH: src/Gaspra.DataPipe.Extract/Gaspra.DataPipe.Extract.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish transform on version change
        id: publish_nuget_transform
        uses: gaspra/gaspra.publishdotnetnuget@v1
        with:
          PROJECT_FILE_PATH: src/Gaspra.DataPipe.Transform/Gaspra.DataPipe.Transform.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish load on version change
        id: publish_nuget_load
        uses: gaspra/gaspra.publishdotnetnuget@v1
        with:
          PROJECT_FILE_PATH: src/Gaspra.DataPipe.Load/Gaspra.DataPipe.Load.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
